In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
print(torch.__version__)

1.12.0+cpu


# Pytorch Fundamentals

Link to pytorch website: https://pytorch.org/

### Creating a Tensor

In PyTorch, everything is a tensor. Tensors are created using `torch.Tensor()`.
https://pytorch.org/docs/stable/tensors.html

In [5]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
# Convert tensor to a Python Int
scalar.item()

7

In [8]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
# Matrix
M = torch.tensor([
    [7, 8],
    [9, 10]
])
M

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
M.ndim

2

In [13]:
M.shape

torch.Size([2, 2])

In [14]:
# Tensor
T = torch.tensor([[
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]])
T

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [15]:
T.ndim

3

In [16]:
T.shape

torch.Size([1, 3, 3])

In [17]:
T[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [18]:
T[0][1]

tensor([4, 5, 6])

### Random Tensors

Random tensors are often used as a starting point when creating models.

Random Tensors: https://pytorch.org/docs/stable/generated/torch.rand.html

In [19]:
# Create a random tensor of size (3, 4)
r = torch.rand(3, 4)
r

tensor([[0.8864, 0.8220, 0.8542, 0.1316],
        [0.7488, 0.7679, 0.9220, 0.0452],
        [0.3735, 0.6115, 0.5734, 0.8293]])

In [20]:
# Create a random tensor with a similar shape to a 224, 224 image
r_img = torch.rand(size=(3, 224, 224))
r_img.shape, r_img.ndim

(torch.Size([3, 224, 224]), 3)

### 0 & 1

In [21]:
# Create a tensor of zeroes
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
# Create a tensor of ones
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
ones.dtype

torch.float32

### Creating a range of tensors

In [32]:
help(torch.arange)

Help on built-in function arange in module torch:

arange(...)
    arange(start=0, end, step=1, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) -> Tensor
    
    Returns a 1-D tensor of size :math:`\left\lceil \frac{\text{end} - \text{start}}{\text{step}} \right\rceil`
    with values from the interval ``[start, end)`` taken with common difference
    :attr:`step` beginning from `start`.
    
    Note that non-integer :attr:`step` is subject to floating point rounding errors when
    comparing against :attr:`end`; to avoid inconsistency, we advise adding a small epsilon to :attr:`end`
    in such cases.
    
    .. math::
        \text{out}_{{i+1}} = \text{out}_{i} + \text{step}
    
    Args:
        start (Number): the starting value for the set of points. Default: ``0``.
        end (Number): the ending value for the set of points
        step (Number): the gap between each pair of adjacent points. Default: ``1``.
    
    Keyword args:
        out 

In [27]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
torch.arange(5, 11)

tensor([ 5,  6,  7,  8,  9, 10])

In [35]:
evens = torch.arange(0, 50, step=2, dtype=torch.int)
evens

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
        36, 38, 40, 42, 44, 46, 48], dtype=torch.int32)

In [36]:
evens.ndim, evens.shape

(1, torch.Size([25]))

### Like Tensors

Creating zero and one tensors in the shape of the provided tensor using `torch.ones_like` and `torch.zeros_like`.

In [40]:
help(torch.ones_like)

Help on built-in function ones_like in module torch:

ones_like(...)
    ones_like(input, *, dtype=None, layout=None, device=None, requires_grad=False, memory_format=torch.preserve_format) -> Tensor
    
    Returns a tensor filled with the scalar value `1`, with the same size as
    :attr:`input`. ``torch.ones_like(input)`` is equivalent to
    ``torch.ones(input.size(), dtype=input.dtype, layout=input.layout, device=input.device)``.
    
    .. warning::
        As of 0.4, this function does not support an :attr:`out` keyword. As an alternative,
        the old ``torch.ones_like(input, out=output)`` is equivalent to
        ``torch.ones(input.size(), out=output)``.
    
    Args:
        input (Tensor): the size of :attr:`input` will determine size of the output tensor.
    
    Keyword arguments:
        dtype (:class:`torch.dtype`, optional): the desired data type of returned Tensor.
            Default: if ``None``, defaults to the dtype of :attr:`input`.
        layout (:class:`t

In [43]:
ones = torch.ones_like(evens)
ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1], dtype=torch.int32)

In [45]:
ones.shape, evens.shape

(torch.Size([25]), torch.Size([25]))

### Empty Tensors

You can create an empty tensor in the provided shape.

In [46]:
help(torch.empty)

Help on built-in function empty in module torch:

empty(...)
    empty(*size, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False, pin_memory=False, memory_format=torch.contiguous_format) -> Tensor
    
    Returns a tensor filled with uninitialized data. The shape of the tensor is
    defined by the variable argument :attr:`size`.
    
    Args:
        size (int...): a sequence of integers defining the shape of the output tensor.
            Can be a variable number of arguments or a collection like a list or tuple.
    
    Keyword args:
        out (Tensor, optional): the output tensor.
        dtype (:class:`torch.dtype`, optional): the desired data type of returned tensor.
            Default: if ``None``, uses a global default (see :func:`torch.set_default_tensor_type`).
        layout (:class:`torch.layout`, optional): the desired layout of returned Tensor.
            Default: ``torch.strided``.
        device (:class:`torch.device`, optional): the 

In [56]:
torch.empty((2, 3), dtype=torch.int32)

tensor([[1664692536,  925907257,  962814262],
        [ 845297764,  828793442, 1647457077]], dtype=torch.int32)

### Tensor Data Types

Tensors support a number of different data types. A single tensor can only have one type data type.

A few of the data types include:

**Floating Point Numbers**
- 16-bit floating point (`torch.float16` or `torch.half`)**
- 16-bit floating point (`torch.bfloat16`)**
- 32 bit floating point (`torch.float32` or `torch.float`) *The default data type*
- 64-bit floating point (`torch.float64` or `torch.double`)

**Complex Numbers**
- 32-bit complex (`torch.complex32` or `torch.chalf`)
- 64-bit complex (`torch.complex64` or `torch.cfloat`)
- 128-bit complex (`torch.complex128` or `torch.cdouble`)

**Integers**
- 8-bit unsigned integer (`torch.uint8`)
- 8-bit signed integer (`torch.int8`)
- 16-bit signed integer (`torch.in16` or `torch.short`)
- 32-bit signed integer (`torch.int32` or `torch.int`)
- 64-bit signed integer (`torch.int64` or `torch.long`)

**Boolean**
- Boolean (`torch.bool`)

**Quantizied Integers**
- quantized 4-bit unsigned integer (`torch.quint4x2`)
- quantized 8-bit unsigned integer (`torch.quint8`)
- quantized 8-bit signed integer (`torch.qint8`)
- quantized 32-bit signed integer (`torch.qint32`)


\** *The difference between `torch.bfloat16` and `torch.float16` lies in the number of bits reserved for exponent and significand bits. Both reserve a single bit for sign. `torch.bfloat16` reserves 8 bits for the exponent and 7 bits for the significand. `torch.float16` reserves 5 bits for the exponent and 10 bits for the significand.*

In [58]:
# float32 is the default data type
float_32_tensor = torch.tensor([1., 2., 3.])
float_32_tensor.dtype 

torch.float32

In [59]:
# If only integers are provided, then int64 is the default data type
int_64_tensor = torch.tensor([1, 2, 3])
int_64_tensor.dtype

torch.int64

In [60]:
# It is possible to convert between different types
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

### Getting key tensor info

1. Tensor data types: `tensor.dtype`
1. Tensor shape: `tensor.shape` or `tensor.size()`
1. Tensore device (which device it's on CPU or GPU): `tensor.device`

In [65]:
tensor = torch.empty(2, 3)
print(tensor)
print("Tensor Data Type:", tensor.dtype)
print("Tensor Shape:", tensor.shape)
print("Tensor Size:", tensor.size())
print("Tensor device:", tensor.device)

tensor([[0.0000e+00, 7.4269e-44, 6.7352e+22],
        [2.1763e-04, 1.3163e+22, 1.0558e-08]])
Tensor Data Type: torch.float32
Tensor Shape: torch.Size([2, 3])
Tensor Size: torch.Size([2, 3])
Tensor device: cpu
